#pragma once

#include "driver/gpio.h"
#include "sdkconfig.h"

#define BOARD_BUTTON_GPIO ((gpio_num_t)CONFIG_IPPHONE_BUTTON_GPIO)
#define BOARD_BUTTON_ACTIVE_LEVEL CONFIG_IPPHONE_BUTTON_ACTIVE_LEVEL

#define BOARD_I2S_MIC_BCLK ((gpio_num_t)CONFIG_IPPHONE_I2S_MIC_BCLK)
#define BOARD_I2S_MIC_WS ((gpio_num_t)CONFIG_IPPHONE_I2S_MIC_WS)
#define BOARD_I2S_MIC_DIN ((gpio_num_t)CONFIG_IPPHONE_I2S_MIC_DIN)

#define BOARD_I2S_SPK_BCLK ((gpio_num_t)CONFIG_IPPHONE_I2S_SPK_BCLK)
#define BOARD_I2S_SPK_WS ((gpio_num_t)CONFIG_IPPHONE_I2S_SPK_WS)
#define BOARD_I2S_SPK_DOUT ((gpio_num_t)CONFIG_IPPHONE_I2S_SPK_DOUT)

#define BOARD_I2C_SDA ((gpio_num_t)CONFIG_IPPHONE_I2C_SDA)
#define BOARD_I2C_SCL ((gpio_num_t)CONFIG_IPPHONE_I2C_SCL)

#define BOARD_LED_GREEN_GPIO ((gpio_num_t)CONFIG_IPPHONE_LED_GREEN_GPIO)
#define BOARD_LED_GREEN_ACTIVE_LEVEL CONFIG_IPPHONE_LED_GREEN_ACTIVE_LEVEL
#define BOARD_LED_RED_GPIO ((gpio_num_t)CONFIG_IPPHONE_LED_RED_GPIO)
#define BOARD_LED_RED_ACTIVE_LEVEL CONFIG_IPPHONE_LED_RED_ACTIVE_LEVEL

#define BOARD_SD_SCK_GPIO ((gpio_num_t)CONFIG_IPPHONE_SD_SCK_GPIO)
#define BOARD_SD_MOSI_GPIO ((gpio_num_t)CONFIG_IPPHONE_SD_MOSI_GPIO)
#define BOARD_SD_MISO_GPIO ((gpio_num_t)CONFIG_IPPHONE_SD_MISO_GPIO)
#define BOARD_SD_CS_GPIO ((gpio_num_t)CONFIG_IPPHONE_SD_CS_GPIO)
